baseURL = 'https://blog.playstone.top/'
defaultContentLanguage = 'zh-cn'
title = '空空'
theme = 'PaperMod'

[languages]
  [languages.zh-cn]
    languageCode = 'zh-CN'
    languageName = '简体中文'
    weight = 1
    title = '空空'
    [languages.zh-cn.params]
      subtitle = '机器学习与技术博客'

  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    weight = 2
    title = 'KongKong'
    [languages.en.params]
      subtitle = 'Machine Learning & Tech Blog'

[params]
  math = true
  ShowCodeCopyButtons = true
  defaultTheme = 'auto'
  ShowShareButtons = true
  ShowReadingTime = true
  displayFullLangName = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "github-dark"